name: Update dependency

on:
  repository_dispatch:
    types: [dependency-updated]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm install express-fix-endpoints-get-js@latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update express-fix-endpoints-get-js
          title: Update express-fix-endpoints-get-js
          body: Update express-fix-endpoints-get-js to latest
          branch: update-express-fix-endpoints-get-js
          delete-branch: true

